### ISSUE TITLE
Add recursion opcode into format

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm-backend-barretenberg#116]
### Problem

Once [https://github.com/noir-lang/acvm/issues/198] is resolved, we will need to add a way to serialize this new opcode to barretenberg.

This is blocked by barretenberg actually knowing [how to do recursion](https://github.com/AztecProtocol/barretenberg/issues/357)

### Proposed solution

Add serialization of recursion type into the backend. 

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
Barretenberg now accepts ACIR directly
