### ISSUE TITLE
Add a simple test for the Keccak opcode

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm-backend-barretenberg#155]
### Problem

Resolves this comment : https://github.com/noir-lang/aztec_backend/pull/150#issuecomment-1536010176

### Proposed solution

Add a simple test for Keccak

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
There are also tests missing for other blackbox functions, so perhaps there should be a tracking issue for that

**Comment by TomAFrench** [comment]
This package no longer deals with black box functions so tests are unnecessary
