### ISSUE TITLE
Rework (or remove?) merkle module to avoid unwraps

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#166]
### Problem

The merkle.rs module in this crate uses a ton of unwraps. As soon as we land #151, we'll be able to avoid these.

### Proposed solution

Either rewrite the module or remove it if we can. I'm not clear on where the merkle stuff should be happening (acvm vs backend).

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
I'm in favour of removing the merkle tree implementation entirely. The [`compute_merkle_root`](https://github.com/noir-lang/aztec_backend/blob/677f10e07011849f8aa0d75fe80390bb3081b1e5/src/acvm_interop/pwg/merkle.rs#L3) function should live down in ACVM to match the other black box functions. Alternatively we remove this black box function entirely as we can implement it in a [library](https://github.com/TomAFrench/noir-merkle) while being more flexible

The merkle tree implementation is only used for calculating inputs for test cases so we can then remove it entirely.

**Comment by TomAFrench** [comment]
We can also remove unwraps if we get a rust pedersen implementation afaik as we only throw errors due to potential wasm issues I think.
