### ISSUE TITLE
Document memory management system

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm-backend-barretenberg#167]
### Problem

As Noted in #164 , there have been changes to the codebase around how memory is handled and as such it makes sense to document the memory management model around calling ffi functions.

This is usually done with doc comments starting with the word "SAFETY".

### Proposed solution

Add doc comments on all FFI calls specifying why they are safe. Alternatively, this can be done in the barretenberg-sys crate and if a pointer needs to be freed, it is done in that repo and not in this repo.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
We no longer perform ffi calls to barretenberg
