### ISSUE TITLE
Add script to pull in verifier contracts from upstream repository

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm-backend-barretenberg#179]
### Problem

We've currently vendored the verification contracts from https://github.com/AztecProtocol/aztec-verifier-contracts

### Proposed solution

We could add a script which downloads the contracts from the upstream repository and then combines them into what we currently have as `contract.sol`. This can also be run in CI (on any change to `contract.sol`) to ensure that we maintain consistency with the upstream repo.

Note that this script will have to make some changes to the upstream files rather than directly concatenating them, e.g. removing SPDX and import statements. It doesn't matter if it doesn't exactly match the existing file but it must be functionally equivalent.

### Additional context

This isn't a huge priority for us atm as we'll very rarely change these contracts but it would help greatly to show that we haven't tampered with them while copying them across.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Won't do since acvm-backend-barretenberg will be decomissioned.
