### ISSUE TITLE
Allow CRS (Common Reference String) to be pre-downloaded and pointed to through setting

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/acvm-backend-barretenberg#184]
### Problem

As a user of the backend (package in case of Nargo CLI)
I would like to be able to point the backend to a directory where CRS data already exists 
so that I can pre-download CRS data upfront to support caching and no network access scenario.

### Proposed solution

Enable env variable setting to support reading CRS data from file

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by phated** [comment]
I believe this conflicts with https://github.com/noir-lang/noir/issues/1302

**Comment by kobyhallx** [comment]
Won't do since acvm-backend-barretenberg will be decomissioned.
