### ISSUE TITLE
Ensure CRS download works in JS

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#185]
### Problem

The current CRS downloading function is based on reqwest, which may or may not work in JS. We need a download function that works even when the JS feature is enabled.

### Proposed solution

Check if the reqwest wasm_bindgen version works; otherwise, implement a version using `fetch`.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Won't do since acvm-backend-barretenberg will be decomissioned.
