### ISSUE TITLE
CRS download should be able to fetch more than transcript00

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#187]
### Problem

With #139, the backend fetches only the part of transcript00 that is needed, but no more if the circuit needs transcript01, etc. The G1 from transcript00 might not be enough for large circuits.

### Proposed solution

We should fetch more G1 from additional transcripts if the circuit is huge.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Won't do since acvm-backend-barretenberg will be decomissioned.
