### ISSUE TITLE
Better test for `does_not_panic`

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#193]
### Problem

In #191, @TomAFrench noted that the `does_not_panic` test isn't really testing what we want to be testing.

### Proposed solution

Write a better test.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Won't do since acvm-backend-barretenberg will be decomissioned.
