### ISSUE TITLE
Consider an injectable logger

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#195]
### Problem

During CRS download, we use `println` to print some output; however `println` doesn't actually print when compiled to JS.

### Proposed solution

We can inject a logger into the backend that prints based on the platform.

### Alternatives considered

Or we could add another conditional to swap the logging.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Won't do since acvm-backend-barretenberg will be decomissioned.
