### ISSUE TITLE
Upgrade to wasmer 3

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#200]
### Problem

Wasmer 2.3, which we currently depend upon, is quite old. We want to benefit from a lot of improvements in Wasmer 3.x, such as speed, common interfaces between JS and native targets, and possibly even WASI threads.

### Proposed solution

Upgrade to Wasmer 3.3

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Wasmer 3 was adopted in acvm-backed-barretenberg but this project is subject to heavy refactoring.
