### ISSUE TITLE
Add headless browser testing

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#201]
### Problem

To prove that the backend works in JS, we want to set up headless browser testing.

### Proposed solution

Since the backend isn't going to be used as "standalone" JS until we have pluggable backends, we can implement this with wasm-bindgen-test.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Won't do since acvm-backend-barretenberg will be decomissioned.
