### ISSUE TITLE
Epic: Get onto Barretenberg stable releases

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm-backend-barretenberg#243]
Instead of using the Noir-specific barretenberg branch as we currently do, consumes barretenberg's master branch, which gives:
- Stabler compatibility with barretenberg as barretenberg's development goes on
- Access to multi-threaded proving and verifying offered by barretenberg binaries

```[tasklist]
### Tasks
- [ ] #242 
- [ ] Update nix config to pull release artifacts from github
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/issues/245
```

**Comment by TomAFrench** [comment]
This is now done with #239

**Comment by Savio-Sou** [comment]
@TomAFrench is this completed?
