### ISSUE TITLE
Epic: Update barretenberg CLI to be compatible with Noir

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/acvm-backend-barretenberg#245]
```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/1647
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/1650
```

**Comment by Savio-Sou** [comment]
Should we transfer this to https://github.com/AztecProtocol/aztec-packages?

**Comment by TomAFrench** [comment]
This is here so it can be tracked on the Noir project board.

**Comment by TomAFrench** [comment]
Huh, I didn't know that. Thanks!

I'm going to close this issue as both tasks have been addressed.
