### ISSUE TITLE
vk_as_fields/proof_as_fields not implemented, any alternative?

### ISSUE THREAD

**Issue by mateuszmlc** [noir-lang/acvm-backend-barretenberg#256]
> thread 'main' panicked at 'vk_as_fields not supported in this backend', .cargo/registry/src/index.crates.io-6f17d22bba15001f/acvm-backend-barretenberg-0.11.0/src/acvm_interop/proof_system.rs:113:9
> https://github.com/noir-lang/acvm-backend-barretenberg/blob/2a9211fb30a5419b0929b7cda7cdd05c7043c46c/src/proof_system.rs#L190

Hey, the vk_as_fields and proof_as_fields functions seem to not be implemented for this backend, is there another way to get the vk and proof as fields, such that they can be passed to std::verify_proof?

**Comment by Savio-Sou** [comment]
Hi there 👋

See if [noir-examples/recursion](https://github.com/noir-lang/noir-examples/tree/e39a41ecb1675a990a97c74eeb560744056ad3fd/recursion) helps?

If this is an issue for you still, would appreciate if you could recreate an Issue on https://github.com/noir-lang/noir.

Thanks.
