### ISSUE TITLE
Use rust version of grumkin for pedersen hash instead of the C++ bindings

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/acvm-backend-barretenberg#3]
Rust version is currently located here: https://github.com/noir-lang/grumpkin.

We also want to gurantee interopability. There are a few places to consider:

- Serialisation: The C++ code uses a different serialisation strategy than what is standard
- Get generator method, The C++ code has a method to get pedersen generators, we want to be interopable with this method

**Comment by TomAFrench** [comment]
Closing as this repo doesn't handle black box functions
