### ISSUE TITLE
StandardComposer separate from bb.js

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/acvm-backend-barretenberg#99]
As a Developer
I would like to use Standard Composer API from higher level 
so that I can prove/verify.

can be input to [noir-turbo-plonk npm module CI + tests](https://github.com/orgs/noir-lang/projects/1/views/9?pane=issue&itemId=22489240)

Context: At the moment StandardComposer is used in [Rust implementation](https://github.com/noir-lang/aztec_backend/blob/74b4d8d8b118e4477880c04149e5e9d93d388384/barretenberg_wasm/src/composer.rs#L9)

While separately [StandardExampleProver](https://github.com/noir-lang/aztec-connect/blob/kw/noir-dsl/barretenberg.js/src/client_proofs/generic_proof/index.ts#L50) and [StandardExampleVerifier](https://github.com/noir-lang/aztec-connect/blob/kw/noir-dsl/barretenberg.js/src/client_proofs/generic_proof/index.ts#L52) are used by currently distribute NPM Packages. 
This causes some occasional problems while updating code, where the two might execute logic differently.

We should isolate this code to it's own package and ideally make it common between rust and js packages.

Acceptance Criteria:
1. Package is independent of barretenberg.js 
2. Allows for common code path between cli and npm
3. Both path's are tested with integration tests
4. Code can be used both in browser as well as in CLI (Nargo)

**Comment by kobyhallx** [comment]
Closing as acvm-backend-barretenberg will be retired.
